// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlHx2_Jx4wvwbzRbQNGzxM5IH7LRCWmRw',
    appId: '1:206147496712:web:c11f7dcf9c38f167fd1abd',
    messagingSenderId: '206147496712',
    projectId: 'food-app-8c7f1',
    authDomain: 'food-app-8c7f1.firebaseapp.com',
    storageBucket: 'food-app-8c7f1.firebasestorage.app',
    measurementId: 'G-6E347R0QKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8y0nqlpRteWHoYwu7-_aVQ--cU6WLMbE',
    appId: '1:206147496712:android:04757b37a5c74f56fd1abd',
    messagingSenderId: '206147496712',
    projectId: 'food-app-8c7f1',
    storageBucket: 'food-app-8c7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQ-Uz29IXnfC6ptpjEv1BLDYaObyjgRM',
    appId: '1:206147496712:ios:757c1d068aab3ab2fd1abd',
    messagingSenderId: '206147496712',
    projectId: 'food-app-8c7f1',
    storageBucket: 'food-app-8c7f1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQ-Uz29IXnfC6ptpjEv1BLDYaObyjgRM',
    appId: '1:206147496712:ios:757c1d068aab3ab2fd1abd',
    messagingSenderId: '206147496712',
    projectId: 'food-app-8c7f1',
    storageBucket: 'food-app-8c7f1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlHx2_Jx4wvwbzRbQNGzxM5IH7LRCWmRw',
    appId: '1:206147496712:web:26888bd22838f6f5fd1abd',
    messagingSenderId: '206147496712',
    projectId: 'food-app-8c7f1',
    authDomain: 'food-app-8c7f1.firebaseapp.com',
    storageBucket: 'food-app-8c7f1.firebasestorage.app',
    measurementId: 'G-F88B2DF886',
  );
}
